version: "3.7"

services:
  postgres:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_DB: photonix
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data

  redis:
    image: redis:3.2.8

  photonix:
    image: damianmoore/photonix:latest
    ports:
      - "8888:80"
    environment:
      ENV: prd
      POSTGRES_HOST: postgres
      POSTGRES_DB: photonix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      REDIS_HOST: redis
      ALLOWED_HOSTS: localhost,example.com
    volumes:
      - /D/docker/photonix/data/photos:/data/photos
      - /D/docker/photonix/data/raw-photos-processed:/data/raw-photos-processed
      - /D/docker/photonix/data/cache:/data/cache
      - /D/docker/photonix/data/models:/data/models
    depends_on:
      - postgres
      - redis
volumes:
  postgres_database:
    external: true